// GENERATED CODE FROM PORK AST CODEGEN
package gay.pizza.pork.ast

enum class NodeType(val parent: NodeType? = null) {
  Node,
  Block(Node),
  Expression(Node),
  BooleanLiteral(Expression),
  Break(Expression),
  CompilationUnit(Node),
  Continue(Expression),
  Declaration(Node),
  Definition(Node),
  DoubleLiteral(Expression),
  ForIn(Expression),
  FunctionCall(Expression),
  FunctionDefinition(Definition),
  If(Expression),
  ImportDeclaration(Declaration),
  InfixOperation(Expression),
  IntegerLiteral(Expression),
  LetAssignment(Expression),
  LetDefinition(Definition),
  ListLiteral(Expression),
  LongLiteral(Expression),
  Native(Node),
  Parentheses(Expression),
  PrefixOperation(Expression),
  SetAssignment(Expression),
  StringLiteral(Expression),
  SuffixOperation(Expression),
  Symbol(Node),
  SymbolReference(Expression),
  VarAssignment(Expression),
  While(Expression)
}
